<?php

/**
 * This is the model base class for the table "notation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notation".
 *
 * Columns in table "notation" available as properties of the model,
 * followed by relations of table "notation" available as properties of the model.
 *
 * @property integer $id
 * @property integer $word_id
 * @property integer $user_id
 * @property integer $note
 *
 * @property Word $word
 * @property User $user
 */
abstract class BaseNotation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'notation';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notation|Notations', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('word_id, user_id, note', 'required'),
			array('word_id, user_id, note', 'numerical', 'integerOnly'=>true),
			array('id, word_id, user_id, note', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'word' => array(self::BELONGS_TO, 'Word', 'word_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'word_id' => null,
			'user_id' => null,
			'note' => Yii::t('app', 'Note'),
			'word' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('word_id', $this->word_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('note', $this->note);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}